# Generated by Django 5.2.1 on 2025-06-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('weeks', models.PositiveIntegerField()),
                ('activity', models.CharField(max_length=255)),
                ('kpi', models.CharField(max_length=255)),
                ('baseline', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('achievement', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
