# Generated by Django 5.2.1 on 2025-06-04 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='achievement',
        ),
        migrations.RemoveField(
            model_name='kpi',
            name='actual',
        ),
    ]
