# Generated by Django 5.2.1 on 2025-06-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_kpidetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpidetails',
            name='achievement',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kpidetails',
            name='progress',
            field=models.FloatField(),
        ),
    ]
